kind: PersistentVolume
apiVersion: v1
metadata:
  name: custom-pv-arti-arti
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
