apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: confluence
spec:
  rules:
  - host: confluence.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: confluence
          servicePort: 8090
