apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: confluence
  name: confluence
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: confluence
      name: confluence
    spec:
      terminationGracePeriodSeconds: 50
      containers:
        - name: confluence
          image: "hoeghh/confluence:6.1.beta2"
          ports:
          - containerPort: 8090
          resources:
            requests:
              cpu: "800m"
              memory: "1.5G"
          env:
          - name: X_PROXY_NAME
            value: "confluence.example.com"
          - name: X_PROXY_PORT
            value: "443"
          - name: X_PROXY_SCHEME
            value: "https"
          - name: X_PROXY_SECURE
            value: "true"
          - name: X_PATH
            value: ""
